// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshtastic/apponly.proto

package org.meshtastic.proto;

public final class AppOnlyProtos {
  private AppOnlyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChannelSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:meshtastic.ChannelSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    java.util.List<org.meshtastic.proto.ChannelProtos.ChannelSettings> 
        getSettingsList();
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    org.meshtastic.proto.ChannelProtos.ChannelSettings getSettings(int index);
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    int getSettingsCount();
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    java.util.List<? extends org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder> 
        getSettingsOrBuilderList();
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder getSettingsOrBuilder(
        int index);

    /**
     * <pre>
     * LoRa config
     * </pre>
     *
     * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
     * @return Whether the loraConfig field is set.
     */
    boolean hasLoraConfig();
    /**
     * <pre>
     * LoRa config
     * </pre>
     *
     * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
     * @return The loraConfig.
     */
    org.meshtastic.proto.ConfigProtos.Config.LoRaConfig getLoraConfig();
    /**
     * <pre>
     * LoRa config
     * </pre>
     *
     * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
     */
    org.meshtastic.proto.ConfigProtos.Config.LoRaConfigOrBuilder getLoraConfigOrBuilder();
  }
  /**
   * <pre>
   * This is the most compact possible representation for a set of channels.
   * It includes only one PRIMARY channel (which must be first) and
   * any SECONDARY channels.
   * No DISABLED channels are included.
   * This abstraction is used only on the the 'app side' of the world (ie python, javascript and android etc) to show a group of Channels as a (long) URL
   * </pre>
   *
   * Protobuf type {@code meshtastic.ChannelSet}
   */
  public static final class ChannelSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:meshtastic.ChannelSet)
      ChannelSetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChannelSet.newBuilder() to construct.
    private ChannelSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelSet() {
      settings_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChannelSet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.meshtastic.proto.AppOnlyProtos.internal_static_meshtastic_ChannelSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.meshtastic.proto.AppOnlyProtos.internal_static_meshtastic_ChannelSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.meshtastic.proto.AppOnlyProtos.ChannelSet.class, org.meshtastic.proto.AppOnlyProtos.ChannelSet.Builder.class);
    }

    public static final int SETTINGS_FIELD_NUMBER = 1;
    private java.util.List<org.meshtastic.proto.ChannelProtos.ChannelSettings> settings_;
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.meshtastic.proto.ChannelProtos.ChannelSettings> getSettingsList() {
      return settings_;
    }
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder> 
        getSettingsOrBuilderList() {
      return settings_;
    }
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    @java.lang.Override
    public int getSettingsCount() {
      return settings_.size();
    }
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    @java.lang.Override
    public org.meshtastic.proto.ChannelProtos.ChannelSettings getSettings(int index) {
      return settings_.get(index);
    }
    /**
     * <pre>
     * Channel list with settings
     * </pre>
     *
     * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
     */
    @java.lang.Override
    public org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder getSettingsOrBuilder(
        int index) {
      return settings_.get(index);
    }

    public static final int LORA_CONFIG_FIELD_NUMBER = 2;
    private org.meshtastic.proto.ConfigProtos.Config.LoRaConfig loraConfig_;
    /**
     * <pre>
     * LoRa config
     * </pre>
     *
     * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
     * @return Whether the loraConfig field is set.
     */
    @java.lang.Override
    public boolean hasLoraConfig() {
      return loraConfig_ != null;
    }
    /**
     * <pre>
     * LoRa config
     * </pre>
     *
     * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
     * @return The loraConfig.
     */
    @java.lang.Override
    public org.meshtastic.proto.ConfigProtos.Config.LoRaConfig getLoraConfig() {
      return loraConfig_ == null ? org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.getDefaultInstance() : loraConfig_;
    }
    /**
     * <pre>
     * LoRa config
     * </pre>
     *
     * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
     */
    @java.lang.Override
    public org.meshtastic.proto.ConfigProtos.Config.LoRaConfigOrBuilder getLoraConfigOrBuilder() {
      return getLoraConfig();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < settings_.size(); i++) {
        output.writeMessage(1, settings_.get(i));
      }
      if (loraConfig_ != null) {
        output.writeMessage(2, getLoraConfig());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < settings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, settings_.get(i));
      }
      if (loraConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoraConfig());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.meshtastic.proto.AppOnlyProtos.ChannelSet)) {
        return super.equals(obj);
      }
      org.meshtastic.proto.AppOnlyProtos.ChannelSet other = (org.meshtastic.proto.AppOnlyProtos.ChannelSet) obj;

      if (!getSettingsList()
          .equals(other.getSettingsList())) return false;
      if (hasLoraConfig() != other.hasLoraConfig()) return false;
      if (hasLoraConfig()) {
        if (!getLoraConfig()
            .equals(other.getLoraConfig())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSettingsCount() > 0) {
        hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getSettingsList().hashCode();
      }
      if (hasLoraConfig()) {
        hash = (37 * hash) + LORA_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getLoraConfig().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.meshtastic.proto.AppOnlyProtos.ChannelSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This is the most compact possible representation for a set of channels.
     * It includes only one PRIMARY channel (which must be first) and
     * any SECONDARY channels.
     * No DISABLED channels are included.
     * This abstraction is used only on the the 'app side' of the world (ie python, javascript and android etc) to show a group of Channels as a (long) URL
     * </pre>
     *
     * Protobuf type {@code meshtastic.ChannelSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:meshtastic.ChannelSet)
        org.meshtastic.proto.AppOnlyProtos.ChannelSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.meshtastic.proto.AppOnlyProtos.internal_static_meshtastic_ChannelSet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.meshtastic.proto.AppOnlyProtos.internal_static_meshtastic_ChannelSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.meshtastic.proto.AppOnlyProtos.ChannelSet.class, org.meshtastic.proto.AppOnlyProtos.ChannelSet.Builder.class);
      }

      // Construct using org.meshtastic.proto.AppOnlyProtos.ChannelSet.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (settingsBuilder_ == null) {
          settings_ = java.util.Collections.emptyList();
        } else {
          settings_ = null;
          settingsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (loraConfigBuilder_ == null) {
          loraConfig_ = null;
        } else {
          loraConfig_ = null;
          loraConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.meshtastic.proto.AppOnlyProtos.internal_static_meshtastic_ChannelSet_descriptor;
      }

      @java.lang.Override
      public org.meshtastic.proto.AppOnlyProtos.ChannelSet getDefaultInstanceForType() {
        return org.meshtastic.proto.AppOnlyProtos.ChannelSet.getDefaultInstance();
      }

      @java.lang.Override
      public org.meshtastic.proto.AppOnlyProtos.ChannelSet build() {
        org.meshtastic.proto.AppOnlyProtos.ChannelSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.meshtastic.proto.AppOnlyProtos.ChannelSet buildPartial() {
        org.meshtastic.proto.AppOnlyProtos.ChannelSet result = new org.meshtastic.proto.AppOnlyProtos.ChannelSet(this);
        int from_bitField0_ = bitField0_;
        if (settingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            settings_ = java.util.Collections.unmodifiableList(settings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.settings_ = settings_;
        } else {
          result.settings_ = settingsBuilder_.build();
        }
        if (loraConfigBuilder_ == null) {
          result.loraConfig_ = loraConfig_;
        } else {
          result.loraConfig_ = loraConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.meshtastic.proto.AppOnlyProtos.ChannelSet) {
          return mergeFrom((org.meshtastic.proto.AppOnlyProtos.ChannelSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.meshtastic.proto.AppOnlyProtos.ChannelSet other) {
        if (other == org.meshtastic.proto.AppOnlyProtos.ChannelSet.getDefaultInstance()) return this;
        if (settingsBuilder_ == null) {
          if (!other.settings_.isEmpty()) {
            if (settings_.isEmpty()) {
              settings_ = other.settings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSettingsIsMutable();
              settings_.addAll(other.settings_);
            }
            onChanged();
          }
        } else {
          if (!other.settings_.isEmpty()) {
            if (settingsBuilder_.isEmpty()) {
              settingsBuilder_.dispose();
              settingsBuilder_ = null;
              settings_ = other.settings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              settingsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSettingsFieldBuilder() : null;
            } else {
              settingsBuilder_.addAllMessages(other.settings_);
            }
          }
        }
        if (other.hasLoraConfig()) {
          mergeLoraConfig(other.getLoraConfig());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.meshtastic.proto.ChannelProtos.ChannelSettings m =
                    input.readMessage(
                        org.meshtastic.proto.ChannelProtos.ChannelSettings.parser(),
                        extensionRegistry);
                if (settingsBuilder_ == null) {
                  ensureSettingsIsMutable();
                  settings_.add(m);
                } else {
                  settingsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getLoraConfigFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.meshtastic.proto.ChannelProtos.ChannelSettings> settings_ =
        java.util.Collections.emptyList();
      private void ensureSettingsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          settings_ = new java.util.ArrayList<org.meshtastic.proto.ChannelProtos.ChannelSettings>(settings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.meshtastic.proto.ChannelProtos.ChannelSettings, org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder, org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder> settingsBuilder_;

      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public java.util.List<org.meshtastic.proto.ChannelProtos.ChannelSettings> getSettingsList() {
        if (settingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(settings_);
        } else {
          return settingsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public int getSettingsCount() {
        if (settingsBuilder_ == null) {
          return settings_.size();
        } else {
          return settingsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public org.meshtastic.proto.ChannelProtos.ChannelSettings getSettings(int index) {
        if (settingsBuilder_ == null) {
          return settings_.get(index);
        } else {
          return settingsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder setSettings(
          int index, org.meshtastic.proto.ChannelProtos.ChannelSettings value) {
        if (settingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSettingsIsMutable();
          settings_.set(index, value);
          onChanged();
        } else {
          settingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder setSettings(
          int index, org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder builderForValue) {
        if (settingsBuilder_ == null) {
          ensureSettingsIsMutable();
          settings_.set(index, builderForValue.build());
          onChanged();
        } else {
          settingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder addSettings(org.meshtastic.proto.ChannelProtos.ChannelSettings value) {
        if (settingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSettingsIsMutable();
          settings_.add(value);
          onChanged();
        } else {
          settingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder addSettings(
          int index, org.meshtastic.proto.ChannelProtos.ChannelSettings value) {
        if (settingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSettingsIsMutable();
          settings_.add(index, value);
          onChanged();
        } else {
          settingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder addSettings(
          org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder builderForValue) {
        if (settingsBuilder_ == null) {
          ensureSettingsIsMutable();
          settings_.add(builderForValue.build());
          onChanged();
        } else {
          settingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder addSettings(
          int index, org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder builderForValue) {
        if (settingsBuilder_ == null) {
          ensureSettingsIsMutable();
          settings_.add(index, builderForValue.build());
          onChanged();
        } else {
          settingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder addAllSettings(
          java.lang.Iterable<? extends org.meshtastic.proto.ChannelProtos.ChannelSettings> values) {
        if (settingsBuilder_ == null) {
          ensureSettingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, settings_);
          onChanged();
        } else {
          settingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder clearSettings() {
        if (settingsBuilder_ == null) {
          settings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          settingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public Builder removeSettings(int index) {
        if (settingsBuilder_ == null) {
          ensureSettingsIsMutable();
          settings_.remove(index);
          onChanged();
        } else {
          settingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder getSettingsBuilder(
          int index) {
        return getSettingsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder getSettingsOrBuilder(
          int index) {
        if (settingsBuilder_ == null) {
          return settings_.get(index);  } else {
          return settingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public java.util.List<? extends org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder> 
           getSettingsOrBuilderList() {
        if (settingsBuilder_ != null) {
          return settingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(settings_);
        }
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder addSettingsBuilder() {
        return getSettingsFieldBuilder().addBuilder(
            org.meshtastic.proto.ChannelProtos.ChannelSettings.getDefaultInstance());
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder addSettingsBuilder(
          int index) {
        return getSettingsFieldBuilder().addBuilder(
            index, org.meshtastic.proto.ChannelProtos.ChannelSettings.getDefaultInstance());
      }
      /**
       * <pre>
       * Channel list with settings
       * </pre>
       *
       * <code>repeated .meshtastic.ChannelSettings settings = 1;</code>
       */
      public java.util.List<org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder> 
           getSettingsBuilderList() {
        return getSettingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.meshtastic.proto.ChannelProtos.ChannelSettings, org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder, org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder> 
          getSettingsFieldBuilder() {
        if (settingsBuilder_ == null) {
          settingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.meshtastic.proto.ChannelProtos.ChannelSettings, org.meshtastic.proto.ChannelProtos.ChannelSettings.Builder, org.meshtastic.proto.ChannelProtos.ChannelSettingsOrBuilder>(
                  settings_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          settings_ = null;
        }
        return settingsBuilder_;
      }

      private org.meshtastic.proto.ConfigProtos.Config.LoRaConfig loraConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.ConfigProtos.Config.LoRaConfig, org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.Builder, org.meshtastic.proto.ConfigProtos.Config.LoRaConfigOrBuilder> loraConfigBuilder_;
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       * @return Whether the loraConfig field is set.
       */
      public boolean hasLoraConfig() {
        return loraConfigBuilder_ != null || loraConfig_ != null;
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       * @return The loraConfig.
       */
      public org.meshtastic.proto.ConfigProtos.Config.LoRaConfig getLoraConfig() {
        if (loraConfigBuilder_ == null) {
          return loraConfig_ == null ? org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.getDefaultInstance() : loraConfig_;
        } else {
          return loraConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       */
      public Builder setLoraConfig(org.meshtastic.proto.ConfigProtos.Config.LoRaConfig value) {
        if (loraConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loraConfig_ = value;
          onChanged();
        } else {
          loraConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       */
      public Builder setLoraConfig(
          org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.Builder builderForValue) {
        if (loraConfigBuilder_ == null) {
          loraConfig_ = builderForValue.build();
          onChanged();
        } else {
          loraConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       */
      public Builder mergeLoraConfig(org.meshtastic.proto.ConfigProtos.Config.LoRaConfig value) {
        if (loraConfigBuilder_ == null) {
          if (loraConfig_ != null) {
            loraConfig_ =
              org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.newBuilder(loraConfig_).mergeFrom(value).buildPartial();
          } else {
            loraConfig_ = value;
          }
          onChanged();
        } else {
          loraConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       */
      public Builder clearLoraConfig() {
        if (loraConfigBuilder_ == null) {
          loraConfig_ = null;
          onChanged();
        } else {
          loraConfig_ = null;
          loraConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       */
      public org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.Builder getLoraConfigBuilder() {
        
        onChanged();
        return getLoraConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       */
      public org.meshtastic.proto.ConfigProtos.Config.LoRaConfigOrBuilder getLoraConfigOrBuilder() {
        if (loraConfigBuilder_ != null) {
          return loraConfigBuilder_.getMessageOrBuilder();
        } else {
          return loraConfig_ == null ?
              org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.getDefaultInstance() : loraConfig_;
        }
      }
      /**
       * <pre>
       * LoRa config
       * </pre>
       *
       * <code>.meshtastic.Config.LoRaConfig lora_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.ConfigProtos.Config.LoRaConfig, org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.Builder, org.meshtastic.proto.ConfigProtos.Config.LoRaConfigOrBuilder> 
          getLoraConfigFieldBuilder() {
        if (loraConfigBuilder_ == null) {
          loraConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.meshtastic.proto.ConfigProtos.Config.LoRaConfig, org.meshtastic.proto.ConfigProtos.Config.LoRaConfig.Builder, org.meshtastic.proto.ConfigProtos.Config.LoRaConfigOrBuilder>(
                  getLoraConfig(),
                  getParentForChildren(),
                  isClean());
          loraConfig_ = null;
        }
        return loraConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:meshtastic.ChannelSet)
    }

    // @@protoc_insertion_point(class_scope:meshtastic.ChannelSet)
    private static final org.meshtastic.proto.AppOnlyProtos.ChannelSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.meshtastic.proto.AppOnlyProtos.ChannelSet();
    }

    public static org.meshtastic.proto.AppOnlyProtos.ChannelSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChannelSet>
        PARSER = new com.google.protobuf.AbstractParser<ChannelSet>() {
      @java.lang.Override
      public ChannelSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChannelSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelSet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.meshtastic.proto.AppOnlyProtos.ChannelSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meshtastic_ChannelSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meshtastic_ChannelSet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030meshtastic/apponly.proto\022\nmeshtastic\032\030" +
      "meshtastic/channel.proto\032\027meshtastic/con" +
      "fig.proto\"o\n\nChannelSet\022-\n\010settings\030\001 \003(" +
      "\0132\033.meshtastic.ChannelSettings\0222\n\013lora_c" +
      "onfig\030\002 \001(\0132\035.meshtastic.Config.LoRaConf" +
      "igBc\n\024org.meshtastic.protoB\rAppOnlyProto" +
      "sZ\"github.com/meshtastic/go/generated\252\002\024" +
      "Meshtastic.Protobufs\272\002\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.meshtastic.proto.ChannelProtos.getDescriptor(),
          org.meshtastic.proto.ConfigProtos.getDescriptor(),
        });
    internal_static_meshtastic_ChannelSet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meshtastic_ChannelSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meshtastic_ChannelSet_descriptor,
        new java.lang.String[] { "Settings", "LoraConfig", });
    org.meshtastic.proto.ChannelProtos.getDescriptor();
    org.meshtastic.proto.ConfigProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
