// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshtastic/clientonly.proto

package org.meshtastic.proto;

public final class ClientOnlyProtos {
  private ClientOnlyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:meshtastic.DeviceProfile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Long name for the node
     * </pre>
     *
     * <code>optional string long_name = 1;</code>
     * @return Whether the longName field is set.
     */
    boolean hasLongName();
    /**
     * <pre>
     * Long name for the node
     * </pre>
     *
     * <code>optional string long_name = 1;</code>
     * @return The longName.
     */
    String getLongName();
    /**
     * <pre>
     * Long name for the node
     * </pre>
     *
     * <code>optional string long_name = 1;</code>
     * @return The bytes for longName.
     */
    com.google.protobuf.ByteString
        getLongNameBytes();

    /**
     * <pre>
     * Short name of the node
     * </pre>
     *
     * <code>optional string short_name = 2;</code>
     * @return Whether the shortName field is set.
     */
    boolean hasShortName();
    /**
     * <pre>
     * Short name of the node
     * </pre>
     *
     * <code>optional string short_name = 2;</code>
     * @return The shortName.
     */
    String getShortName();
    /**
     * <pre>
     * Short name of the node
     * </pre>
     *
     * <code>optional string short_name = 2;</code>
     * @return The bytes for shortName.
     */
    com.google.protobuf.ByteString
        getShortNameBytes();

    /**
     * <pre>
     * The url of the channels from our node
     * </pre>
     *
     * <code>optional string channel_url = 3;</code>
     * @return Whether the channelUrl field is set.
     */
    boolean hasChannelUrl();
    /**
     * <pre>
     * The url of the channels from our node
     * </pre>
     *
     * <code>optional string channel_url = 3;</code>
     * @return The channelUrl.
     */
    String getChannelUrl();
    /**
     * <pre>
     * The url of the channels from our node
     * </pre>
     *
     * <code>optional string channel_url = 3;</code>
     * @return The bytes for channelUrl.
     */
    com.google.protobuf.ByteString
        getChannelUrlBytes();

    /**
     * <pre>
     * The Config of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalConfig config = 4;</code>
     * @return Whether the config field is set.
     */
    boolean hasConfig();
    /**
     * <pre>
     * The Config of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalConfig config = 4;</code>
     * @return The config.
     */
    org.meshtastic.proto.LocalOnlyProtos.LocalConfig getConfig();
    /**
     * <pre>
     * The Config of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalConfig config = 4;</code>
     */
    org.meshtastic.proto.LocalOnlyProtos.LocalConfigOrBuilder getConfigOrBuilder();

    /**
     * <pre>
     * The ModuleConfig of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
     * @return Whether the moduleConfig field is set.
     */
    boolean hasModuleConfig();
    /**
     * <pre>
     * The ModuleConfig of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
     * @return The moduleConfig.
     */
    org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig getModuleConfig();
    /**
     * <pre>
     * The ModuleConfig of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
     */
    org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfigOrBuilder getModuleConfigOrBuilder();

    /**
     * <pre>
     * Fixed position data
     * </pre>
     *
     * <code>optional .meshtastic.Position fixed_position = 6;</code>
     * @return Whether the fixedPosition field is set.
     */
    boolean hasFixedPosition();
    /**
     * <pre>
     * Fixed position data
     * </pre>
     *
     * <code>optional .meshtastic.Position fixed_position = 6;</code>
     * @return The fixedPosition.
     */
    org.meshtastic.proto.MeshProtos.Position getFixedPosition();
    /**
     * <pre>
     * Fixed position data
     * </pre>
     *
     * <code>optional .meshtastic.Position fixed_position = 6;</code>
     */
    org.meshtastic.proto.MeshProtos.PositionOrBuilder getFixedPositionOrBuilder();

    /**
     * <pre>
     * Ringtone for ExternalNotification
     * </pre>
     *
     * <code>optional string ringtone = 7;</code>
     * @return Whether the ringtone field is set.
     */
    boolean hasRingtone();
    /**
     * <pre>
     * Ringtone for ExternalNotification
     * </pre>
     *
     * <code>optional string ringtone = 7;</code>
     * @return The ringtone.
     */
    String getRingtone();
    /**
     * <pre>
     * Ringtone for ExternalNotification
     * </pre>
     *
     * <code>optional string ringtone = 7;</code>
     * @return The bytes for ringtone.
     */
    com.google.protobuf.ByteString
        getRingtoneBytes();

    /**
     * <pre>
     * Predefined messages for CannedMessage
     * </pre>
     *
     * <code>optional string canned_messages = 8;</code>
     * @return Whether the cannedMessages field is set.
     */
    boolean hasCannedMessages();
    /**
     * <pre>
     * Predefined messages for CannedMessage
     * </pre>
     *
     * <code>optional string canned_messages = 8;</code>
     * @return The cannedMessages.
     */
    String getCannedMessages();
    /**
     * <pre>
     * Predefined messages for CannedMessage
     * </pre>
     *
     * <code>optional string canned_messages = 8;</code>
     * @return The bytes for cannedMessages.
     */
    com.google.protobuf.ByteString
        getCannedMessagesBytes();
  }
  /**
   * <pre>
   * This abstraction is used to contain any configuration for provisioning a node on any client.
   * It is useful for importing and exporting configurations.
   * </pre>
   *
   * Protobuf type {@code meshtastic.DeviceProfile}
   */
  public static final class DeviceProfile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:meshtastic.DeviceProfile)
      DeviceProfileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceProfile.newBuilder() to construct.
    private DeviceProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceProfile() {
      longName_ = "";
      shortName_ = "";
      channelUrl_ = "";
      ringtone_ = "";
      cannedMessages_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceProfile();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.meshtastic.proto.ClientOnlyProtos.internal_static_meshtastic_DeviceProfile_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.meshtastic.proto.ClientOnlyProtos.internal_static_meshtastic_DeviceProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.meshtastic.proto.ClientOnlyProtos.DeviceProfile.class, org.meshtastic.proto.ClientOnlyProtos.DeviceProfile.Builder.class);
    }

    private int bitField0_;
    public static final int LONG_NAME_FIELD_NUMBER = 1;
    private volatile Object longName_;
    /**
     * <pre>
     * Long name for the node
     * </pre>
     *
     * <code>optional string long_name = 1;</code>
     * @return Whether the longName field is set.
     */
    @Override
    public boolean hasLongName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Long name for the node
     * </pre>
     *
     * <code>optional string long_name = 1;</code>
     * @return The longName.
     */
    @Override
    public String getLongName() {
      Object ref = longName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        longName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Long name for the node
     * </pre>
     *
     * <code>optional string long_name = 1;</code>
     * @return The bytes for longName.
     */
    @Override
    public com.google.protobuf.ByteString
        getLongNameBytes() {
      Object ref = longName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        longName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORT_NAME_FIELD_NUMBER = 2;
    private volatile Object shortName_;
    /**
     * <pre>
     * Short name of the node
     * </pre>
     *
     * <code>optional string short_name = 2;</code>
     * @return Whether the shortName field is set.
     */
    @Override
    public boolean hasShortName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Short name of the node
     * </pre>
     *
     * <code>optional string short_name = 2;</code>
     * @return The shortName.
     */
    @Override
    public String getShortName() {
      Object ref = shortName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        shortName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Short name of the node
     * </pre>
     *
     * <code>optional string short_name = 2;</code>
     * @return The bytes for shortName.
     */
    @Override
    public com.google.protobuf.ByteString
        getShortNameBytes() {
      Object ref = shortName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        shortName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_URL_FIELD_NUMBER = 3;
    private volatile Object channelUrl_;
    /**
     * <pre>
     * The url of the channels from our node
     * </pre>
     *
     * <code>optional string channel_url = 3;</code>
     * @return Whether the channelUrl field is set.
     */
    @Override
    public boolean hasChannelUrl() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The url of the channels from our node
     * </pre>
     *
     * <code>optional string channel_url = 3;</code>
     * @return The channelUrl.
     */
    @Override
    public String getChannelUrl() {
      Object ref = channelUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        channelUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The url of the channels from our node
     * </pre>
     *
     * <code>optional string channel_url = 3;</code>
     * @return The bytes for channelUrl.
     */
    @Override
    public com.google.protobuf.ByteString
        getChannelUrlBytes() {
      Object ref = channelUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channelUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIG_FIELD_NUMBER = 4;
    private org.meshtastic.proto.LocalOnlyProtos.LocalConfig config_;
    /**
     * <pre>
     * The Config of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalConfig config = 4;</code>
     * @return Whether the config field is set.
     */
    @Override
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The Config of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalConfig config = 4;</code>
     * @return The config.
     */
    @Override
    public org.meshtastic.proto.LocalOnlyProtos.LocalConfig getConfig() {
      return config_ == null ? org.meshtastic.proto.LocalOnlyProtos.LocalConfig.getDefaultInstance() : config_;
    }
    /**
     * <pre>
     * The Config of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalConfig config = 4;</code>
     */
    @Override
    public org.meshtastic.proto.LocalOnlyProtos.LocalConfigOrBuilder getConfigOrBuilder() {
      return config_ == null ? org.meshtastic.proto.LocalOnlyProtos.LocalConfig.getDefaultInstance() : config_;
    }

    public static final int MODULE_CONFIG_FIELD_NUMBER = 5;
    private org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig moduleConfig_;
    /**
     * <pre>
     * The ModuleConfig of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
     * @return Whether the moduleConfig field is set.
     */
    @Override
    public boolean hasModuleConfig() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * The ModuleConfig of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
     * @return The moduleConfig.
     */
    @Override
    public org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig getModuleConfig() {
      return moduleConfig_ == null ? org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.getDefaultInstance() : moduleConfig_;
    }
    /**
     * <pre>
     * The ModuleConfig of the node
     * </pre>
     *
     * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
     */
    @Override
    public org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfigOrBuilder getModuleConfigOrBuilder() {
      return moduleConfig_ == null ? org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.getDefaultInstance() : moduleConfig_;
    }

    public static final int FIXED_POSITION_FIELD_NUMBER = 6;
    private org.meshtastic.proto.MeshProtos.Position fixedPosition_;
    /**
     * <pre>
     * Fixed position data
     * </pre>
     *
     * <code>optional .meshtastic.Position fixed_position = 6;</code>
     * @return Whether the fixedPosition field is set.
     */
    @Override
    public boolean hasFixedPosition() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Fixed position data
     * </pre>
     *
     * <code>optional .meshtastic.Position fixed_position = 6;</code>
     * @return The fixedPosition.
     */
    @Override
    public org.meshtastic.proto.MeshProtos.Position getFixedPosition() {
      return fixedPosition_ == null ? org.meshtastic.proto.MeshProtos.Position.getDefaultInstance() : fixedPosition_;
    }
    /**
     * <pre>
     * Fixed position data
     * </pre>
     *
     * <code>optional .meshtastic.Position fixed_position = 6;</code>
     */
    @Override
    public org.meshtastic.proto.MeshProtos.PositionOrBuilder getFixedPositionOrBuilder() {
      return fixedPosition_ == null ? org.meshtastic.proto.MeshProtos.Position.getDefaultInstance() : fixedPosition_;
    }

    public static final int RINGTONE_FIELD_NUMBER = 7;
    private volatile Object ringtone_;
    /**
     * <pre>
     * Ringtone for ExternalNotification
     * </pre>
     *
     * <code>optional string ringtone = 7;</code>
     * @return Whether the ringtone field is set.
     */
    @Override
    public boolean hasRingtone() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Ringtone for ExternalNotification
     * </pre>
     *
     * <code>optional string ringtone = 7;</code>
     * @return The ringtone.
     */
    @Override
    public String getRingtone() {
      Object ref = ringtone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ringtone_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Ringtone for ExternalNotification
     * </pre>
     *
     * <code>optional string ringtone = 7;</code>
     * @return The bytes for ringtone.
     */
    @Override
    public com.google.protobuf.ByteString
        getRingtoneBytes() {
      Object ref = ringtone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ringtone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANNED_MESSAGES_FIELD_NUMBER = 8;
    private volatile Object cannedMessages_;
    /**
     * <pre>
     * Predefined messages for CannedMessage
     * </pre>
     *
     * <code>optional string canned_messages = 8;</code>
     * @return Whether the cannedMessages field is set.
     */
    @Override
    public boolean hasCannedMessages() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Predefined messages for CannedMessage
     * </pre>
     *
     * <code>optional string canned_messages = 8;</code>
     * @return The cannedMessages.
     */
    @Override
    public String getCannedMessages() {
      Object ref = cannedMessages_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cannedMessages_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Predefined messages for CannedMessage
     * </pre>
     *
     * <code>optional string canned_messages = 8;</code>
     * @return The bytes for cannedMessages.
     */
    @Override
    public com.google.protobuf.ByteString
        getCannedMessagesBytes() {
      Object ref = cannedMessages_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cannedMessages_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, longName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, shortName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, channelUrl_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getConfig());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeMessage(5, getModuleConfig());
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeMessage(6, getFixedPosition());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ringtone_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, cannedMessages_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, longName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, shortName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, channelUrl_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getConfig());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getModuleConfig());
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getFixedPosition());
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ringtone_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, cannedMessages_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.meshtastic.proto.ClientOnlyProtos.DeviceProfile)) {
        return super.equals(obj);
      }
      org.meshtastic.proto.ClientOnlyProtos.DeviceProfile other = (org.meshtastic.proto.ClientOnlyProtos.DeviceProfile) obj;

      if (hasLongName() != other.hasLongName()) return false;
      if (hasLongName()) {
        if (!getLongName()
            .equals(other.getLongName())) return false;
      }
      if (hasShortName() != other.hasShortName()) return false;
      if (hasShortName()) {
        if (!getShortName()
            .equals(other.getShortName())) return false;
      }
      if (hasChannelUrl() != other.hasChannelUrl()) return false;
      if (hasChannelUrl()) {
        if (!getChannelUrl()
            .equals(other.getChannelUrl())) return false;
      }
      if (hasConfig() != other.hasConfig()) return false;
      if (hasConfig()) {
        if (!getConfig()
            .equals(other.getConfig())) return false;
      }
      if (hasModuleConfig() != other.hasModuleConfig()) return false;
      if (hasModuleConfig()) {
        if (!getModuleConfig()
            .equals(other.getModuleConfig())) return false;
      }
      if (hasFixedPosition() != other.hasFixedPosition()) return false;
      if (hasFixedPosition()) {
        if (!getFixedPosition()
            .equals(other.getFixedPosition())) return false;
      }
      if (hasRingtone() != other.hasRingtone()) return false;
      if (hasRingtone()) {
        if (!getRingtone()
            .equals(other.getRingtone())) return false;
      }
      if (hasCannedMessages() != other.hasCannedMessages()) return false;
      if (hasCannedMessages()) {
        if (!getCannedMessages()
            .equals(other.getCannedMessages())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLongName()) {
        hash = (37 * hash) + LONG_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getLongName().hashCode();
      }
      if (hasShortName()) {
        hash = (37 * hash) + SHORT_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getShortName().hashCode();
      }
      if (hasChannelUrl()) {
        hash = (37 * hash) + CHANNEL_URL_FIELD_NUMBER;
        hash = (53 * hash) + getChannelUrl().hashCode();
      }
      if (hasConfig()) {
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getConfig().hashCode();
      }
      if (hasModuleConfig()) {
        hash = (37 * hash) + MODULE_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getModuleConfig().hashCode();
      }
      if (hasFixedPosition()) {
        hash = (37 * hash) + FIXED_POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getFixedPosition().hashCode();
      }
      if (hasRingtone()) {
        hash = (37 * hash) + RINGTONE_FIELD_NUMBER;
        hash = (53 * hash) + getRingtone().hashCode();
      }
      if (hasCannedMessages()) {
        hash = (37 * hash) + CANNED_MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getCannedMessages().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.meshtastic.proto.ClientOnlyProtos.DeviceProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This abstraction is used to contain any configuration for provisioning a node on any client.
     * It is useful for importing and exporting configurations.
     * </pre>
     *
     * Protobuf type {@code meshtastic.DeviceProfile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:meshtastic.DeviceProfile)
        org.meshtastic.proto.ClientOnlyProtos.DeviceProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.meshtastic.proto.ClientOnlyProtos.internal_static_meshtastic_DeviceProfile_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.meshtastic.proto.ClientOnlyProtos.internal_static_meshtastic_DeviceProfile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.meshtastic.proto.ClientOnlyProtos.DeviceProfile.class, org.meshtastic.proto.ClientOnlyProtos.DeviceProfile.Builder.class);
      }

      // Construct using org.meshtastic.proto.ClientOnlyProtos.DeviceProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConfigFieldBuilder();
          getModuleConfigFieldBuilder();
          getFixedPositionFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        longName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        shortName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        channelUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (configBuilder_ == null) {
          config_ = null;
        } else {
          configBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (moduleConfigBuilder_ == null) {
          moduleConfig_ = null;
        } else {
          moduleConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (fixedPositionBuilder_ == null) {
          fixedPosition_ = null;
        } else {
          fixedPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        ringtone_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        cannedMessages_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.meshtastic.proto.ClientOnlyProtos.internal_static_meshtastic_DeviceProfile_descriptor;
      }

      @Override
      public org.meshtastic.proto.ClientOnlyProtos.DeviceProfile getDefaultInstanceForType() {
        return org.meshtastic.proto.ClientOnlyProtos.DeviceProfile.getDefaultInstance();
      }

      @Override
      public org.meshtastic.proto.ClientOnlyProtos.DeviceProfile build() {
        org.meshtastic.proto.ClientOnlyProtos.DeviceProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.meshtastic.proto.ClientOnlyProtos.DeviceProfile buildPartial() {
        org.meshtastic.proto.ClientOnlyProtos.DeviceProfile result = new org.meshtastic.proto.ClientOnlyProtos.DeviceProfile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.longName_ = longName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.shortName_ = shortName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.channelUrl_ = channelUrl_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (configBuilder_ == null) {
            result.config_ = config_;
          } else {
            result.config_ = configBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          if (moduleConfigBuilder_ == null) {
            result.moduleConfig_ = moduleConfig_;
          } else {
            result.moduleConfig_ = moduleConfigBuilder_.build();
          }
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          if (fixedPositionBuilder_ == null) {
            result.fixedPosition_ = fixedPosition_;
          } else {
            result.fixedPosition_ = fixedPositionBuilder_.build();
          }
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ringtone_ = ringtone_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cannedMessages_ = cannedMessages_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.meshtastic.proto.ClientOnlyProtos.DeviceProfile) {
          return mergeFrom((org.meshtastic.proto.ClientOnlyProtos.DeviceProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.meshtastic.proto.ClientOnlyProtos.DeviceProfile other) {
        if (other == org.meshtastic.proto.ClientOnlyProtos.DeviceProfile.getDefaultInstance()) return this;
        if (other.hasLongName()) {
          bitField0_ |= 0x00000001;
          longName_ = other.longName_;
          onChanged();
        }
        if (other.hasShortName()) {
          bitField0_ |= 0x00000002;
          shortName_ = other.shortName_;
          onChanged();
        }
        if (other.hasChannelUrl()) {
          bitField0_ |= 0x00000004;
          channelUrl_ = other.channelUrl_;
          onChanged();
        }
        if (other.hasConfig()) {
          mergeConfig(other.getConfig());
        }
        if (other.hasModuleConfig()) {
          mergeModuleConfig(other.getModuleConfig());
        }
        if (other.hasFixedPosition()) {
          mergeFixedPosition(other.getFixedPosition());
        }
        if (other.hasRingtone()) {
          bitField0_ |= 0x00000040;
          ringtone_ = other.ringtone_;
          onChanged();
        }
        if (other.hasCannedMessages()) {
          bitField0_ |= 0x00000080;
          cannedMessages_ = other.cannedMessages_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                longName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                shortName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                channelUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getConfigFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getModuleConfigFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getFixedPositionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                ringtone_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                cannedMessages_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object longName_ = "";
      /**
       * <pre>
       * Long name for the node
       * </pre>
       *
       * <code>optional string long_name = 1;</code>
       * @return Whether the longName field is set.
       */
      public boolean hasLongName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Long name for the node
       * </pre>
       *
       * <code>optional string long_name = 1;</code>
       * @return The longName.
       */
      public String getLongName() {
        Object ref = longName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          longName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Long name for the node
       * </pre>
       *
       * <code>optional string long_name = 1;</code>
       * @return The bytes for longName.
       */
      public com.google.protobuf.ByteString
          getLongNameBytes() {
        Object ref = longName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          longName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Long name for the node
       * </pre>
       *
       * <code>optional string long_name = 1;</code>
       * @param value The longName to set.
       * @return This builder for chaining.
       */
      public Builder setLongName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        longName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Long name for the node
       * </pre>
       *
       * <code>optional string long_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        longName_ = getDefaultInstance().getLongName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Long name for the node
       * </pre>
       *
       * <code>optional string long_name = 1;</code>
       * @param value The bytes for longName to set.
       * @return This builder for chaining.
       */
      public Builder setLongNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        longName_ = value;
        onChanged();
        return this;
      }

      private Object shortName_ = "";
      /**
       * <pre>
       * Short name of the node
       * </pre>
       *
       * <code>optional string short_name = 2;</code>
       * @return Whether the shortName field is set.
       */
      public boolean hasShortName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Short name of the node
       * </pre>
       *
       * <code>optional string short_name = 2;</code>
       * @return The shortName.
       */
      public String getShortName() {
        Object ref = shortName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          shortName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Short name of the node
       * </pre>
       *
       * <code>optional string short_name = 2;</code>
       * @return The bytes for shortName.
       */
      public com.google.protobuf.ByteString
          getShortNameBytes() {
        Object ref = shortName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          shortName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Short name of the node
       * </pre>
       *
       * <code>optional string short_name = 2;</code>
       * @param value The shortName to set.
       * @return This builder for chaining.
       */
      public Builder setShortName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        shortName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Short name of the node
       * </pre>
       *
       * <code>optional string short_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearShortName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        shortName_ = getDefaultInstance().getShortName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Short name of the node
       * </pre>
       *
       * <code>optional string short_name = 2;</code>
       * @param value The bytes for shortName to set.
       * @return This builder for chaining.
       */
      public Builder setShortNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        shortName_ = value;
        onChanged();
        return this;
      }

      private Object channelUrl_ = "";
      /**
       * <pre>
       * The url of the channels from our node
       * </pre>
       *
       * <code>optional string channel_url = 3;</code>
       * @return Whether the channelUrl field is set.
       */
      public boolean hasChannelUrl() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * The url of the channels from our node
       * </pre>
       *
       * <code>optional string channel_url = 3;</code>
       * @return The channelUrl.
       */
      public String getChannelUrl() {
        Object ref = channelUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          channelUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * The url of the channels from our node
       * </pre>
       *
       * <code>optional string channel_url = 3;</code>
       * @return The bytes for channelUrl.
       */
      public com.google.protobuf.ByteString
          getChannelUrlBytes() {
        Object ref = channelUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channelUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The url of the channels from our node
       * </pre>
       *
       * <code>optional string channel_url = 3;</code>
       * @param value The channelUrl to set.
       * @return This builder for chaining.
       */
      public Builder setChannelUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        channelUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The url of the channels from our node
       * </pre>
       *
       * <code>optional string channel_url = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        channelUrl_ = getDefaultInstance().getChannelUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The url of the channels from our node
       * </pre>
       *
       * <code>optional string channel_url = 3;</code>
       * @param value The bytes for channelUrl to set.
       * @return This builder for chaining.
       */
      public Builder setChannelUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        channelUrl_ = value;
        onChanged();
        return this;
      }

      private org.meshtastic.proto.LocalOnlyProtos.LocalConfig config_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.LocalOnlyProtos.LocalConfig, org.meshtastic.proto.LocalOnlyProtos.LocalConfig.Builder, org.meshtastic.proto.LocalOnlyProtos.LocalConfigOrBuilder> configBuilder_;
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       * @return Whether the config field is set.
       */
      public boolean hasConfig() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       * @return The config.
       */
      public org.meshtastic.proto.LocalOnlyProtos.LocalConfig getConfig() {
        if (configBuilder_ == null) {
          return config_ == null ? org.meshtastic.proto.LocalOnlyProtos.LocalConfig.getDefaultInstance() : config_;
        } else {
          return configBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       */
      public Builder setConfig(org.meshtastic.proto.LocalOnlyProtos.LocalConfig value) {
        if (configBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          config_ = value;
          onChanged();
        } else {
          configBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       */
      public Builder setConfig(
          org.meshtastic.proto.LocalOnlyProtos.LocalConfig.Builder builderForValue) {
        if (configBuilder_ == null) {
          config_ = builderForValue.build();
          onChanged();
        } else {
          configBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       */
      public Builder mergeConfig(org.meshtastic.proto.LocalOnlyProtos.LocalConfig value) {
        if (configBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              config_ != null &&
              config_ != org.meshtastic.proto.LocalOnlyProtos.LocalConfig.getDefaultInstance()) {
            config_ =
              org.meshtastic.proto.LocalOnlyProtos.LocalConfig.newBuilder(config_).mergeFrom(value).buildPartial();
          } else {
            config_ = value;
          }
          onChanged();
        } else {
          configBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       */
      public Builder clearConfig() {
        if (configBuilder_ == null) {
          config_ = null;
          onChanged();
        } else {
          configBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       */
      public org.meshtastic.proto.LocalOnlyProtos.LocalConfig.Builder getConfigBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       */
      public org.meshtastic.proto.LocalOnlyProtos.LocalConfigOrBuilder getConfigOrBuilder() {
        if (configBuilder_ != null) {
          return configBuilder_.getMessageOrBuilder();
        } else {
          return config_ == null ?
              org.meshtastic.proto.LocalOnlyProtos.LocalConfig.getDefaultInstance() : config_;
        }
      }
      /**
       * <pre>
       * The Config of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalConfig config = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.LocalOnlyProtos.LocalConfig, org.meshtastic.proto.LocalOnlyProtos.LocalConfig.Builder, org.meshtastic.proto.LocalOnlyProtos.LocalConfigOrBuilder> 
          getConfigFieldBuilder() {
        if (configBuilder_ == null) {
          configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.meshtastic.proto.LocalOnlyProtos.LocalConfig, org.meshtastic.proto.LocalOnlyProtos.LocalConfig.Builder, org.meshtastic.proto.LocalOnlyProtos.LocalConfigOrBuilder>(
                  getConfig(),
                  getParentForChildren(),
                  isClean());
          config_ = null;
        }
        return configBuilder_;
      }

      private org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig moduleConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig, org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.Builder, org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfigOrBuilder> moduleConfigBuilder_;
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       * @return Whether the moduleConfig field is set.
       */
      public boolean hasModuleConfig() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       * @return The moduleConfig.
       */
      public org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig getModuleConfig() {
        if (moduleConfigBuilder_ == null) {
          return moduleConfig_ == null ? org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.getDefaultInstance() : moduleConfig_;
        } else {
          return moduleConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       */
      public Builder setModuleConfig(org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig value) {
        if (moduleConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          moduleConfig_ = value;
          onChanged();
        } else {
          moduleConfigBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       */
      public Builder setModuleConfig(
          org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.Builder builderForValue) {
        if (moduleConfigBuilder_ == null) {
          moduleConfig_ = builderForValue.build();
          onChanged();
        } else {
          moduleConfigBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       */
      public Builder mergeModuleConfig(org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig value) {
        if (moduleConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
              moduleConfig_ != null &&
              moduleConfig_ != org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.getDefaultInstance()) {
            moduleConfig_ =
              org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.newBuilder(moduleConfig_).mergeFrom(value).buildPartial();
          } else {
            moduleConfig_ = value;
          }
          onChanged();
        } else {
          moduleConfigBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       */
      public Builder clearModuleConfig() {
        if (moduleConfigBuilder_ == null) {
          moduleConfig_ = null;
          onChanged();
        } else {
          moduleConfigBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       */
      public org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.Builder getModuleConfigBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getModuleConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       */
      public org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfigOrBuilder getModuleConfigOrBuilder() {
        if (moduleConfigBuilder_ != null) {
          return moduleConfigBuilder_.getMessageOrBuilder();
        } else {
          return moduleConfig_ == null ?
              org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.getDefaultInstance() : moduleConfig_;
        }
      }
      /**
       * <pre>
       * The ModuleConfig of the node
       * </pre>
       *
       * <code>optional .meshtastic.LocalModuleConfig module_config = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig, org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.Builder, org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfigOrBuilder> 
          getModuleConfigFieldBuilder() {
        if (moduleConfigBuilder_ == null) {
          moduleConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig, org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfig.Builder, org.meshtastic.proto.LocalOnlyProtos.LocalModuleConfigOrBuilder>(
                  getModuleConfig(),
                  getParentForChildren(),
                  isClean());
          moduleConfig_ = null;
        }
        return moduleConfigBuilder_;
      }

      private org.meshtastic.proto.MeshProtos.Position fixedPosition_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.MeshProtos.Position, org.meshtastic.proto.MeshProtos.Position.Builder, org.meshtastic.proto.MeshProtos.PositionOrBuilder> fixedPositionBuilder_;
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       * @return Whether the fixedPosition field is set.
       */
      public boolean hasFixedPosition() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       * @return The fixedPosition.
       */
      public org.meshtastic.proto.MeshProtos.Position getFixedPosition() {
        if (fixedPositionBuilder_ == null) {
          return fixedPosition_ == null ? org.meshtastic.proto.MeshProtos.Position.getDefaultInstance() : fixedPosition_;
        } else {
          return fixedPositionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       */
      public Builder setFixedPosition(org.meshtastic.proto.MeshProtos.Position value) {
        if (fixedPositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fixedPosition_ = value;
          onChanged();
        } else {
          fixedPositionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       */
      public Builder setFixedPosition(
          org.meshtastic.proto.MeshProtos.Position.Builder builderForValue) {
        if (fixedPositionBuilder_ == null) {
          fixedPosition_ = builderForValue.build();
          onChanged();
        } else {
          fixedPositionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       */
      public Builder mergeFixedPosition(org.meshtastic.proto.MeshProtos.Position value) {
        if (fixedPositionBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
              fixedPosition_ != null &&
              fixedPosition_ != org.meshtastic.proto.MeshProtos.Position.getDefaultInstance()) {
            fixedPosition_ =
              org.meshtastic.proto.MeshProtos.Position.newBuilder(fixedPosition_).mergeFrom(value).buildPartial();
          } else {
            fixedPosition_ = value;
          }
          onChanged();
        } else {
          fixedPositionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       */
      public Builder clearFixedPosition() {
        if (fixedPositionBuilder_ == null) {
          fixedPosition_ = null;
          onChanged();
        } else {
          fixedPositionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       */
      public org.meshtastic.proto.MeshProtos.Position.Builder getFixedPositionBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getFixedPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       */
      public org.meshtastic.proto.MeshProtos.PositionOrBuilder getFixedPositionOrBuilder() {
        if (fixedPositionBuilder_ != null) {
          return fixedPositionBuilder_.getMessageOrBuilder();
        } else {
          return fixedPosition_ == null ?
              org.meshtastic.proto.MeshProtos.Position.getDefaultInstance() : fixedPosition_;
        }
      }
      /**
       * <pre>
       * Fixed position data
       * </pre>
       *
       * <code>optional .meshtastic.Position fixed_position = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.MeshProtos.Position, org.meshtastic.proto.MeshProtos.Position.Builder, org.meshtastic.proto.MeshProtos.PositionOrBuilder> 
          getFixedPositionFieldBuilder() {
        if (fixedPositionBuilder_ == null) {
          fixedPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.meshtastic.proto.MeshProtos.Position, org.meshtastic.proto.MeshProtos.Position.Builder, org.meshtastic.proto.MeshProtos.PositionOrBuilder>(
                  getFixedPosition(),
                  getParentForChildren(),
                  isClean());
          fixedPosition_ = null;
        }
        return fixedPositionBuilder_;
      }

      private Object ringtone_ = "";
      /**
       * <pre>
       * Ringtone for ExternalNotification
       * </pre>
       *
       * <code>optional string ringtone = 7;</code>
       * @return Whether the ringtone field is set.
       */
      public boolean hasRingtone() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * Ringtone for ExternalNotification
       * </pre>
       *
       * <code>optional string ringtone = 7;</code>
       * @return The ringtone.
       */
      public String getRingtone() {
        Object ref = ringtone_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ringtone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Ringtone for ExternalNotification
       * </pre>
       *
       * <code>optional string ringtone = 7;</code>
       * @return The bytes for ringtone.
       */
      public com.google.protobuf.ByteString
          getRingtoneBytes() {
        Object ref = ringtone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ringtone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Ringtone for ExternalNotification
       * </pre>
       *
       * <code>optional string ringtone = 7;</code>
       * @param value The ringtone to set.
       * @return This builder for chaining.
       */
      public Builder setRingtone(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ringtone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ringtone for ExternalNotification
       * </pre>
       *
       * <code>optional string ringtone = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRingtone() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ringtone_ = getDefaultInstance().getRingtone();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ringtone for ExternalNotification
       * </pre>
       *
       * <code>optional string ringtone = 7;</code>
       * @param value The bytes for ringtone to set.
       * @return This builder for chaining.
       */
      public Builder setRingtoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000040;
        ringtone_ = value;
        onChanged();
        return this;
      }

      private Object cannedMessages_ = "";
      /**
       * <pre>
       * Predefined messages for CannedMessage
       * </pre>
       *
       * <code>optional string canned_messages = 8;</code>
       * @return Whether the cannedMessages field is set.
       */
      public boolean hasCannedMessages() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * Predefined messages for CannedMessage
       * </pre>
       *
       * <code>optional string canned_messages = 8;</code>
       * @return The cannedMessages.
       */
      public String getCannedMessages() {
        Object ref = cannedMessages_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cannedMessages_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Predefined messages for CannedMessage
       * </pre>
       *
       * <code>optional string canned_messages = 8;</code>
       * @return The bytes for cannedMessages.
       */
      public com.google.protobuf.ByteString
          getCannedMessagesBytes() {
        Object ref = cannedMessages_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cannedMessages_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Predefined messages for CannedMessage
       * </pre>
       *
       * <code>optional string canned_messages = 8;</code>
       * @param value The cannedMessages to set.
       * @return This builder for chaining.
       */
      public Builder setCannedMessages(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        cannedMessages_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Predefined messages for CannedMessage
       * </pre>
       *
       * <code>optional string canned_messages = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCannedMessages() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cannedMessages_ = getDefaultInstance().getCannedMessages();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Predefined messages for CannedMessage
       * </pre>
       *
       * <code>optional string canned_messages = 8;</code>
       * @param value The bytes for cannedMessages to set.
       * @return This builder for chaining.
       */
      public Builder setCannedMessagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000080;
        cannedMessages_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:meshtastic.DeviceProfile)
    }

    // @@protoc_insertion_point(class_scope:meshtastic.DeviceProfile)
    private static final org.meshtastic.proto.ClientOnlyProtos.DeviceProfile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.meshtastic.proto.ClientOnlyProtos.DeviceProfile();
    }

    public static org.meshtastic.proto.ClientOnlyProtos.DeviceProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceProfile>
        PARSER = new com.google.protobuf.AbstractParser<DeviceProfile>() {
      @Override
      public DeviceProfile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DeviceProfile> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DeviceProfile> getParserForType() {
      return PARSER;
    }

    @Override
    public org.meshtastic.proto.ClientOnlyProtos.DeviceProfile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meshtastic_DeviceProfile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meshtastic_DeviceProfile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033meshtastic/clientonly.proto\022\nmeshtasti" +
      "c\032\032meshtastic/localonly.proto\032\025meshtasti" +
      "c/mesh.proto\"\251\003\n\rDeviceProfile\022\026\n\tlong_n" +
      "ame\030\001 \001(\tH\000\210\001\001\022\027\n\nshort_name\030\002 \001(\tH\001\210\001\001\022" +
      "\030\n\013channel_url\030\003 \001(\tH\002\210\001\001\022,\n\006config\030\004 \001(" +
      "\0132\027.meshtastic.LocalConfigH\003\210\001\001\0229\n\rmodul" +
      "e_config\030\005 \001(\0132\035.meshtastic.LocalModuleC" +
      "onfigH\004\210\001\001\0221\n\016fixed_position\030\006 \001(\0132\024.mes" +
      "htastic.PositionH\005\210\001\001\022\025\n\010ringtone\030\007 \001(\tH" +
      "\006\210\001\001\022\034\n\017canned_messages\030\010 \001(\tH\007\210\001\001B\014\n\n_l" +
      "ong_nameB\r\n\013_short_nameB\016\n\014_channel_urlB" +
      "\t\n\007_configB\020\n\016_module_configB\021\n\017_fixed_p" +
      "ositionB\013\n\t_ringtoneB\022\n\020_canned_messages" +
      "Bf\n\024org.meshtastic.protoB\020ClientOnlyProt" +
      "osZ\"github.com/meshtastic/go/generated\252\002" +
      "\024Meshtastic.Protobufs\272\002\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.meshtastic.proto.LocalOnlyProtos.getDescriptor(),
          org.meshtastic.proto.MeshProtos.getDescriptor(),
        });
    internal_static_meshtastic_DeviceProfile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meshtastic_DeviceProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meshtastic_DeviceProfile_descriptor,
        new String[] { "LongName", "ShortName", "ChannelUrl", "Config", "ModuleConfig", "FixedPosition", "Ringtone", "CannedMessages", "LongName", "ShortName", "ChannelUrl", "Config", "ModuleConfig", "FixedPosition", "Ringtone", "CannedMessages", });
    org.meshtastic.proto.LocalOnlyProtos.getDescriptor();
    org.meshtastic.proto.MeshProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
