// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshtastic/interdevice.proto

package org.meshtastic.proto;

public final class InterdeviceProtos {
  private InterdeviceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code meshtastic.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACK = 0;</code>
     */
    ACK(0),
    /**
     * <pre>
     * in ms
     * </pre>
     *
     * <code>COLLECT_INTERVAL = 160;</code>
     */
    COLLECT_INTERVAL(160),
    /**
     * <pre>
     * duration ms
     * </pre>
     *
     * <code>BEEP_ON = 161;</code>
     */
    BEEP_ON(161),
    /**
     * <pre>
     * cancel prematurely
     * </pre>
     *
     * <code>BEEP_OFF = 162;</code>
     */
    BEEP_OFF(162),
    /**
     * <code>SHUTDOWN = 163;</code>
     */
    SHUTDOWN(163),
    /**
     * <code>POWER_ON = 164;</code>
     */
    POWER_ON(164),
    /**
     * <code>SCD41_TEMP = 176;</code>
     */
    SCD41_TEMP(176),
    /**
     * <code>SCD41_HUMIDITY = 177;</code>
     */
    SCD41_HUMIDITY(177),
    /**
     * <code>SCD41_CO2 = 178;</code>
     */
    SCD41_CO2(178),
    /**
     * <code>AHT20_TEMP = 179;</code>
     */
    AHT20_TEMP(179),
    /**
     * <code>AHT20_HUMIDITY = 180;</code>
     */
    AHT20_HUMIDITY(180),
    /**
     * <code>TVOC_INDEX = 181;</code>
     */
    TVOC_INDEX(181),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACK = 0;</code>
     */
    public static final int ACK_VALUE = 0;
    /**
     * <pre>
     * in ms
     * </pre>
     *
     * <code>COLLECT_INTERVAL = 160;</code>
     */
    public static final int COLLECT_INTERVAL_VALUE = 160;
    /**
     * <pre>
     * duration ms
     * </pre>
     *
     * <code>BEEP_ON = 161;</code>
     */
    public static final int BEEP_ON_VALUE = 161;
    /**
     * <pre>
     * cancel prematurely
     * </pre>
     *
     * <code>BEEP_OFF = 162;</code>
     */
    public static final int BEEP_OFF_VALUE = 162;
    /**
     * <code>SHUTDOWN = 163;</code>
     */
    public static final int SHUTDOWN_VALUE = 163;
    /**
     * <code>POWER_ON = 164;</code>
     */
    public static final int POWER_ON_VALUE = 164;
    /**
     * <code>SCD41_TEMP = 176;</code>
     */
    public static final int SCD41_TEMP_VALUE = 176;
    /**
     * <code>SCD41_HUMIDITY = 177;</code>
     */
    public static final int SCD41_HUMIDITY_VALUE = 177;
    /**
     * <code>SCD41_CO2 = 178;</code>
     */
    public static final int SCD41_CO2_VALUE = 178;
    /**
     * <code>AHT20_TEMP = 179;</code>
     */
    public static final int AHT20_TEMP_VALUE = 179;
    /**
     * <code>AHT20_HUMIDITY = 180;</code>
     */
    public static final int AHT20_HUMIDITY_VALUE = 180;
    /**
     * <code>TVOC_INDEX = 181;</code>
     */
    public static final int TVOC_INDEX_VALUE = 181;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return ACK;
        case 160: return COLLECT_INTERVAL;
        case 161: return BEEP_ON;
        case 162: return BEEP_OFF;
        case 163: return SHUTDOWN;
        case 164: return POWER_ON;
        case 176: return SCD41_TEMP;
        case 177: return SCD41_HUMIDITY;
        case 178: return SCD41_CO2;
        case 179: return AHT20_TEMP;
        case 180: return AHT20_HUMIDITY;
        case 181: return TVOC_INDEX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.meshtastic.proto.InterdeviceProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:meshtastic.MessageType)
  }

  public interface SensorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:meshtastic.SensorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The message type
     * </pre>
     *
     * <code>.meshtastic.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * The message type
     * </pre>
     *
     * <code>.meshtastic.MessageType type = 1;</code>
     * @return The type.
     */
    org.meshtastic.proto.InterdeviceProtos.MessageType getType();

    /**
     * <code>float float_value = 2;</code>
     * @return Whether the floatValue field is set.
     */
    boolean hasFloatValue();
    /**
     * <code>float float_value = 2;</code>
     * @return The floatValue.
     */
    float getFloatValue();

    /**
     * <code>uint32 uint32_value = 3;</code>
     * @return Whether the uint32Value field is set.
     */
    boolean hasUint32Value();
    /**
     * <code>uint32 uint32_value = 3;</code>
     * @return The uint32Value.
     */
    int getUint32Value();

    public org.meshtastic.proto.InterdeviceProtos.SensorData.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code meshtastic.SensorData}
   */
  public static final class SensorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:meshtastic.SensorData)
      SensorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorData.newBuilder() to construct.
    private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorData() {
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SensorData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_SensorData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_SensorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.meshtastic.proto.InterdeviceProtos.SensorData.class, org.meshtastic.proto.InterdeviceProtos.SensorData.Builder.class);
    }

    private int dataCase_ = 0;
    private Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      FLOAT_VALUE(2),
      UINT32_VALUE(3),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 2: return FLOAT_VALUE;
          case 3: return UINT32_VALUE;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * The message type
     * </pre>
     *
     * <code>.meshtastic.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * The message type
     * </pre>
     *
     * <code>.meshtastic.MessageType type = 1;</code>
     * @return The type.
     */
    @Override public org.meshtastic.proto.InterdeviceProtos.MessageType getType() {
      @SuppressWarnings("deprecation")
      org.meshtastic.proto.InterdeviceProtos.MessageType result = org.meshtastic.proto.InterdeviceProtos.MessageType.valueOf(type_);
      return result == null ? org.meshtastic.proto.InterdeviceProtos.MessageType.UNRECOGNIZED : result;
    }

    public static final int FLOAT_VALUE_FIELD_NUMBER = 2;
    /**
     * <code>float float_value = 2;</code>
     * @return Whether the floatValue field is set.
     */
    @Override
    public boolean hasFloatValue() {
      return dataCase_ == 2;
    }
    /**
     * <code>float float_value = 2;</code>
     * @return The floatValue.
     */
    @Override
    public float getFloatValue() {
      if (dataCase_ == 2) {
        return (Float) data_;
      }
      return 0F;
    }

    public static final int UINT32_VALUE_FIELD_NUMBER = 3;
    /**
     * <code>uint32 uint32_value = 3;</code>
     * @return Whether the uint32Value field is set.
     */
    @Override
    public boolean hasUint32Value() {
      return dataCase_ == 3;
    }
    /**
     * <code>uint32 uint32_value = 3;</code>
     * @return The uint32Value.
     */
    @Override
    public int getUint32Value() {
      if (dataCase_ == 3) {
        return (Integer) data_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != org.meshtastic.proto.InterdeviceProtos.MessageType.ACK.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (dataCase_ == 2) {
        output.writeFloat(
            2, (float)((Float) data_));
      }
      if (dataCase_ == 3) {
        output.writeUInt32(
            3, (int)((Integer) data_));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != org.meshtastic.proto.InterdeviceProtos.MessageType.ACK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(
              2, (float)((Float) data_));
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
              3, (int)((Integer) data_));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.meshtastic.proto.InterdeviceProtos.SensorData)) {
        return super.equals(obj);
      }
      org.meshtastic.proto.InterdeviceProtos.SensorData other = (org.meshtastic.proto.InterdeviceProtos.SensorData) obj;

      if (type_ != other.type_) return false;
      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 2:
          if (Float.floatToIntBits(getFloatValue())
              != Float.floatToIntBits(
                  other.getFloatValue())) return false;
          break;
        case 3:
          if (getUint32Value()
              != other.getUint32Value()) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (dataCase_) {
        case 2:
          hash = (37 * hash) + FLOAT_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + Float.floatToIntBits(
              getFloatValue());
          break;
        case 3:
          hash = (37 * hash) + UINT32_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getUint32Value();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.InterdeviceProtos.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.meshtastic.proto.InterdeviceProtos.SensorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code meshtastic.SensorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:meshtastic.SensorData)
        org.meshtastic.proto.InterdeviceProtos.SensorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_SensorData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_SensorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.meshtastic.proto.InterdeviceProtos.SensorData.class, org.meshtastic.proto.InterdeviceProtos.SensorData.Builder.class);
      }

      // Construct using org.meshtastic.proto.InterdeviceProtos.SensorData.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_SensorData_descriptor;
      }

      @Override
      public org.meshtastic.proto.InterdeviceProtos.SensorData getDefaultInstanceForType() {
        return org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance();
      }

      @Override
      public org.meshtastic.proto.InterdeviceProtos.SensorData build() {
        org.meshtastic.proto.InterdeviceProtos.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.meshtastic.proto.InterdeviceProtos.SensorData buildPartial() {
        org.meshtastic.proto.InterdeviceProtos.SensorData result = new org.meshtastic.proto.InterdeviceProtos.SensorData(this);
        result.type_ = type_;
        if (dataCase_ == 2) {
          result.data_ = data_;
        }
        if (dataCase_ == 3) {
          result.data_ = data_;
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.meshtastic.proto.InterdeviceProtos.SensorData) {
          return mergeFrom((org.meshtastic.proto.InterdeviceProtos.SensorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.meshtastic.proto.InterdeviceProtos.SensorData other) {
        if (other == org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getDataCase()) {
          case FLOAT_VALUE: {
            setFloatValue(other.getFloatValue());
            break;
          }
          case UINT32_VALUE: {
            setUint32Value(other.getUint32Value());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();

                break;
              } // case 8
              case 21: {
                data_ = input.readFloat();
                dataCase_ = 2;
                break;
              } // case 21
              case 24: {
                data_ = input.readUInt32();
                dataCase_ = 3;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int dataCase_ = 0;
      private Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <pre>
       * The message type
       * </pre>
       *
       * <code>.meshtastic.MessageType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * The message type
       * </pre>
       *
       * <code>.meshtastic.MessageType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message type
       * </pre>
       *
       * <code>.meshtastic.MessageType type = 1;</code>
       * @return The type.
       */
      @Override
      public org.meshtastic.proto.InterdeviceProtos.MessageType getType() {
        @SuppressWarnings("deprecation")
        org.meshtastic.proto.InterdeviceProtos.MessageType result = org.meshtastic.proto.InterdeviceProtos.MessageType.valueOf(type_);
        return result == null ? org.meshtastic.proto.InterdeviceProtos.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The message type
       * </pre>
       *
       * <code>.meshtastic.MessageType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.meshtastic.proto.InterdeviceProtos.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message type
       * </pre>
       *
       * <code>.meshtastic.MessageType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>float float_value = 2;</code>
       * @return Whether the floatValue field is set.
       */
      public boolean hasFloatValue() {
        return dataCase_ == 2;
      }
      /**
       * <code>float float_value = 2;</code>
       * @return The floatValue.
       */
      public float getFloatValue() {
        if (dataCase_ == 2) {
          return (Float) data_;
        }
        return 0F;
      }
      /**
       * <code>float float_value = 2;</code>
       * @param value The floatValue to set.
       * @return This builder for chaining.
       */
      public Builder setFloatValue(float value) {
        dataCase_ = 2;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float float_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloatValue() {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>uint32 uint32_value = 3;</code>
       * @return Whether the uint32Value field is set.
       */
      public boolean hasUint32Value() {
        return dataCase_ == 3;
      }
      /**
       * <code>uint32 uint32_value = 3;</code>
       * @return The uint32Value.
       */
      public int getUint32Value() {
        if (dataCase_ == 3) {
          return (Integer) data_;
        }
        return 0;
      }
      /**
       * <code>uint32 uint32_value = 3;</code>
       * @param value The uint32Value to set.
       * @return This builder for chaining.
       */
      public Builder setUint32Value(int value) {
        dataCase_ = 3;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uint32_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUint32Value() {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:meshtastic.SensorData)
    }

    // @@protoc_insertion_point(class_scope:meshtastic.SensorData)
    private static final org.meshtastic.proto.InterdeviceProtos.SensorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.meshtastic.proto.InterdeviceProtos.SensorData();
    }

    public static org.meshtastic.proto.InterdeviceProtos.SensorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorData>
        PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
      @Override
      public SensorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SensorData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SensorData> getParserForType() {
      return PARSER;
    }

    @Override
    public org.meshtastic.proto.InterdeviceProtos.SensorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InterdeviceMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:meshtastic.InterdeviceMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nmea = 1;</code>
     * @return Whether the nmea field is set.
     */
    boolean hasNmea();
    /**
     * <code>string nmea = 1;</code>
     * @return The nmea.
     */
    String getNmea();
    /**
     * <code>string nmea = 1;</code>
     * @return The bytes for nmea.
     */
    com.google.protobuf.ByteString
        getNmeaBytes();

    /**
     * <code>.meshtastic.SensorData sensor = 2;</code>
     * @return Whether the sensor field is set.
     */
    boolean hasSensor();
    /**
     * <code>.meshtastic.SensorData sensor = 2;</code>
     * @return The sensor.
     */
    org.meshtastic.proto.InterdeviceProtos.SensorData getSensor();
    /**
     * <code>.meshtastic.SensorData sensor = 2;</code>
     */
    org.meshtastic.proto.InterdeviceProtos.SensorDataOrBuilder getSensorOrBuilder();

    public org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code meshtastic.InterdeviceMessage}
   */
  public static final class InterdeviceMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:meshtastic.InterdeviceMessage)
      InterdeviceMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InterdeviceMessage.newBuilder() to construct.
    private InterdeviceMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InterdeviceMessage() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new InterdeviceMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_InterdeviceMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_InterdeviceMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.class, org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.Builder.class);
    }

    private int dataCase_ = 0;
    private Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      NMEA(1),
      SENSOR(2),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1: return NMEA;
          case 2: return SENSOR;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int NMEA_FIELD_NUMBER = 1;
    /**
     * <code>string nmea = 1;</code>
     * @return Whether the nmea field is set.
     */
    public boolean hasNmea() {
      return dataCase_ == 1;
    }
    /**
     * <code>string nmea = 1;</code>
     * @return The nmea.
     */
    public String getNmea() {
      Object ref = "";
      if (dataCase_ == 1) {
        ref = data_;
      }
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (dataCase_ == 1) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string nmea = 1;</code>
     * @return The bytes for nmea.
     */
    public com.google.protobuf.ByteString
        getNmeaBytes() {
      Object ref = "";
      if (dataCase_ == 1) {
        ref = data_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (dataCase_ == 1) {
          data_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSOR_FIELD_NUMBER = 2;
    /**
     * <code>.meshtastic.SensorData sensor = 2;</code>
     * @return Whether the sensor field is set.
     */
    @Override
    public boolean hasSensor() {
      return dataCase_ == 2;
    }
    /**
     * <code>.meshtastic.SensorData sensor = 2;</code>
     * @return The sensor.
     */
    @Override
    public org.meshtastic.proto.InterdeviceProtos.SensorData getSensor() {
      if (dataCase_ == 2) {
         return (org.meshtastic.proto.InterdeviceProtos.SensorData) data_;
      }
      return org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance();
    }
    /**
     * <code>.meshtastic.SensorData sensor = 2;</code>
     */
    @Override
    public org.meshtastic.proto.InterdeviceProtos.SensorDataOrBuilder getSensorOrBuilder() {
      if (dataCase_ == 2) {
         return (org.meshtastic.proto.InterdeviceProtos.SensorData) data_;
      }
      return org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
      }
      if (dataCase_ == 2) {
        output.writeMessage(2, (org.meshtastic.proto.InterdeviceProtos.SensorData) data_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (org.meshtastic.proto.InterdeviceProtos.SensorData) data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage)) {
        return super.equals(obj);
      }
      org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage other = (org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage) obj;

      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 1:
          if (!getNmea()
              .equals(other.getNmea())) return false;
          break;
        case 2:
          if (!getSensor()
              .equals(other.getSensor())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + NMEA_FIELD_NUMBER;
          hash = (53 * hash) + getNmea().hashCode();
          break;
        case 2:
          hash = (37 * hash) + SENSOR_FIELD_NUMBER;
          hash = (53 * hash) + getSensor().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code meshtastic.InterdeviceMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:meshtastic.InterdeviceMessage)
        org.meshtastic.proto.InterdeviceProtos.InterdeviceMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_InterdeviceMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_InterdeviceMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.class, org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.Builder.class);
      }

      // Construct using org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        if (sensorBuilder_ != null) {
          sensorBuilder_.clear();
        }
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.meshtastic.proto.InterdeviceProtos.internal_static_meshtastic_InterdeviceMessage_descriptor;
      }

      @Override
      public org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage getDefaultInstanceForType() {
        return org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.getDefaultInstance();
      }

      @Override
      public org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage build() {
        org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage buildPartial() {
        org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage result = new org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage(this);
        if (dataCase_ == 1) {
          result.data_ = data_;
        }
        if (dataCase_ == 2) {
          if (sensorBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = sensorBuilder_.build();
          }
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage) {
          return mergeFrom((org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage other) {
        if (other == org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage.getDefaultInstance()) return this;
        switch (other.getDataCase()) {
          case NMEA: {
            dataCase_ = 1;
            data_ = other.data_;
            onChanged();
            break;
          }
          case SENSOR: {
            mergeSensor(other.getSensor());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();
                dataCase_ = 1;
                data_ = s;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSensorFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int dataCase_ = 0;
      private Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>string nmea = 1;</code>
       * @return Whether the nmea field is set.
       */
      @Override
      public boolean hasNmea() {
        return dataCase_ == 1;
      }
      /**
       * <code>string nmea = 1;</code>
       * @return The nmea.
       */
      @Override
      public String getNmea() {
        Object ref = "";
        if (dataCase_ == 1) {
          ref = data_;
        }
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (dataCase_ == 1) {
            data_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nmea = 1;</code>
       * @return The bytes for nmea.
       */
      @Override
      public com.google.protobuf.ByteString
          getNmeaBytes() {
        Object ref = "";
        if (dataCase_ == 1) {
          ref = data_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          if (dataCase_ == 1) {
            data_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nmea = 1;</code>
       * @param value The nmea to set.
       * @return This builder for chaining.
       */
      public Builder setNmea(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 1;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nmea = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNmea() {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string nmea = 1;</code>
       * @param value The bytes for nmea to set.
       * @return This builder for chaining.
       */
      public Builder setNmeaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        dataCase_ = 1;
        data_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.InterdeviceProtos.SensorData, org.meshtastic.proto.InterdeviceProtos.SensorData.Builder, org.meshtastic.proto.InterdeviceProtos.SensorDataOrBuilder> sensorBuilder_;
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       * @return Whether the sensor field is set.
       */
      @Override
      public boolean hasSensor() {
        return dataCase_ == 2;
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       * @return The sensor.
       */
      @Override
      public org.meshtastic.proto.InterdeviceProtos.SensorData getSensor() {
        if (sensorBuilder_ == null) {
          if (dataCase_ == 2) {
            return (org.meshtastic.proto.InterdeviceProtos.SensorData) data_;
          }
          return org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance();
        } else {
          if (dataCase_ == 2) {
            return sensorBuilder_.getMessage();
          }
          return org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance();
        }
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       */
      public Builder setSensor(org.meshtastic.proto.InterdeviceProtos.SensorData value) {
        if (sensorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          sensorBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       */
      public Builder setSensor(
          org.meshtastic.proto.InterdeviceProtos.SensorData.Builder builderForValue) {
        if (sensorBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          sensorBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       */
      public Builder mergeSensor(org.meshtastic.proto.InterdeviceProtos.SensorData value) {
        if (sensorBuilder_ == null) {
          if (dataCase_ == 2 &&
              data_ != org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance()) {
            data_ = org.meshtastic.proto.InterdeviceProtos.SensorData.newBuilder((org.meshtastic.proto.InterdeviceProtos.SensorData) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 2) {
            sensorBuilder_.mergeFrom(value);
          } else {
            sensorBuilder_.setMessage(value);
          }
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       */
      public Builder clearSensor() {
        if (sensorBuilder_ == null) {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
          }
          sensorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       */
      public org.meshtastic.proto.InterdeviceProtos.SensorData.Builder getSensorBuilder() {
        return getSensorFieldBuilder().getBuilder();
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       */
      @Override
      public org.meshtastic.proto.InterdeviceProtos.SensorDataOrBuilder getSensorOrBuilder() {
        if ((dataCase_ == 2) && (sensorBuilder_ != null)) {
          return sensorBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 2) {
            return (org.meshtastic.proto.InterdeviceProtos.SensorData) data_;
          }
          return org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance();
        }
      }
      /**
       * <code>.meshtastic.SensorData sensor = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.meshtastic.proto.InterdeviceProtos.SensorData, org.meshtastic.proto.InterdeviceProtos.SensorData.Builder, org.meshtastic.proto.InterdeviceProtos.SensorDataOrBuilder> 
          getSensorFieldBuilder() {
        if (sensorBuilder_ == null) {
          if (!(dataCase_ == 2)) {
            data_ = org.meshtastic.proto.InterdeviceProtos.SensorData.getDefaultInstance();
          }
          sensorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.meshtastic.proto.InterdeviceProtos.SensorData, org.meshtastic.proto.InterdeviceProtos.SensorData.Builder, org.meshtastic.proto.InterdeviceProtos.SensorDataOrBuilder>(
                  (org.meshtastic.proto.InterdeviceProtos.SensorData) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 2;
        onChanged();;
        return sensorBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:meshtastic.InterdeviceMessage)
    }

    // @@protoc_insertion_point(class_scope:meshtastic.InterdeviceMessage)
    private static final org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage();
    }

    public static org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InterdeviceMessage>
        PARSER = new com.google.protobuf.AbstractParser<InterdeviceMessage>() {
      @Override
      public InterdeviceMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InterdeviceMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InterdeviceMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public org.meshtastic.proto.InterdeviceProtos.InterdeviceMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meshtastic_SensorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meshtastic_SensorData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meshtastic_InterdeviceMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meshtastic_InterdeviceMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034meshtastic/interdevice.proto\022\nmeshtast" +
      "ic\"j\n\nSensorData\022%\n\004type\030\001 \001(\0162\027.meshtas" +
      "tic.MessageType\022\025\n\013float_value\030\002 \001(\002H\000\022\026" +
      "\n\014uint32_value\030\003 \001(\rH\000B\006\n\004data\"V\n\022Interd" +
      "eviceMessage\022\016\n\004nmea\030\001 \001(\tH\000\022(\n\006sensor\030\002" +
      " \001(\0132\026.meshtastic.SensorDataH\000B\006\n\004data*\325" +
      "\001\n\013MessageType\022\007\n\003ACK\020\000\022\025\n\020COLLECT_INTER" +
      "VAL\020\240\001\022\014\n\007BEEP_ON\020\241\001\022\r\n\010BEEP_OFF\020\242\001\022\r\n\010S" +
      "HUTDOWN\020\243\001\022\r\n\010POWER_ON\020\244\001\022\017\n\nSCD41_TEMP\020" +
      "\260\001\022\023\n\016SCD41_HUMIDITY\020\261\001\022\016\n\tSCD41_CO2\020\262\001\022" +
      "\017\n\nAHT20_TEMP\020\263\001\022\023\n\016AHT20_HUMIDITY\020\264\001\022\017\n" +
      "\nTVOC_INDEX\020\265\001Bg\n\024org.meshtastic.protoB\021" +
      "InterdeviceProtosZ\"github.com/meshtastic" +
      "/go/generated\252\002\024Meshtastic.Protobufs\272\002\000b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_meshtastic_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meshtastic_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meshtastic_SensorData_descriptor,
        new String[] { "Type", "FloatValue", "Uint32Value", "Data", });
    internal_static_meshtastic_InterdeviceMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meshtastic_InterdeviceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meshtastic_InterdeviceMessage_descriptor,
        new String[] { "Nmea", "Sensor", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
