// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshtastic/paxcount.proto

package org.meshtastic.proto;

public final class PaxcountProtos {
  private PaxcountProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PaxcountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:meshtastic.Paxcount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * seen Wifi devices
     * </pre>
     *
     * <code>uint32 wifi = 1;</code>
     * @return The wifi.
     */
    int getWifi();

    /**
     * <pre>
     * Seen BLE devices
     * </pre>
     *
     * <code>uint32 ble = 2;</code>
     * @return The ble.
     */
    int getBle();

    /**
     * <pre>
     * Uptime in seconds
     * </pre>
     *
     * <code>uint32 uptime = 3;</code>
     * @return The uptime.
     */
    int getUptime();
  }
  /**
   * <pre>
   * TODO: REPLACE
   * </pre>
   *
   * Protobuf type {@code meshtastic.Paxcount}
   */
  public static final class Paxcount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:meshtastic.Paxcount)
      PaxcountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Paxcount.newBuilder() to construct.
    private Paxcount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Paxcount() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Paxcount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.meshtastic.proto.PaxcountProtos.internal_static_meshtastic_Paxcount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.meshtastic.proto.PaxcountProtos.internal_static_meshtastic_Paxcount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.meshtastic.proto.PaxcountProtos.Paxcount.class, org.meshtastic.proto.PaxcountProtos.Paxcount.Builder.class);
    }

    public static final int WIFI_FIELD_NUMBER = 1;
    private int wifi_;
    /**
     * <pre>
     * seen Wifi devices
     * </pre>
     *
     * <code>uint32 wifi = 1;</code>
     * @return The wifi.
     */
    @java.lang.Override
    public int getWifi() {
      return wifi_;
    }

    public static final int BLE_FIELD_NUMBER = 2;
    private int ble_;
    /**
     * <pre>
     * Seen BLE devices
     * </pre>
     *
     * <code>uint32 ble = 2;</code>
     * @return The ble.
     */
    @java.lang.Override
    public int getBle() {
      return ble_;
    }

    public static final int UPTIME_FIELD_NUMBER = 3;
    private int uptime_;
    /**
     * <pre>
     * Uptime in seconds
     * </pre>
     *
     * <code>uint32 uptime = 3;</code>
     * @return The uptime.
     */
    @java.lang.Override
    public int getUptime() {
      return uptime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (wifi_ != 0) {
        output.writeUInt32(1, wifi_);
      }
      if (ble_ != 0) {
        output.writeUInt32(2, ble_);
      }
      if (uptime_ != 0) {
        output.writeUInt32(3, uptime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (wifi_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, wifi_);
      }
      if (ble_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, ble_);
      }
      if (uptime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, uptime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.meshtastic.proto.PaxcountProtos.Paxcount)) {
        return super.equals(obj);
      }
      org.meshtastic.proto.PaxcountProtos.Paxcount other = (org.meshtastic.proto.PaxcountProtos.Paxcount) obj;

      if (getWifi()
          != other.getWifi()) return false;
      if (getBle()
          != other.getBle()) return false;
      if (getUptime()
          != other.getUptime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIFI_FIELD_NUMBER;
      hash = (53 * hash) + getWifi();
      hash = (37 * hash) + BLE_FIELD_NUMBER;
      hash = (53 * hash) + getBle();
      hash = (37 * hash) + UPTIME_FIELD_NUMBER;
      hash = (53 * hash) + getUptime();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.meshtastic.proto.PaxcountProtos.Paxcount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.meshtastic.proto.PaxcountProtos.Paxcount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * TODO: REPLACE
     * </pre>
     *
     * Protobuf type {@code meshtastic.Paxcount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:meshtastic.Paxcount)
        org.meshtastic.proto.PaxcountProtos.PaxcountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.meshtastic.proto.PaxcountProtos.internal_static_meshtastic_Paxcount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.meshtastic.proto.PaxcountProtos.internal_static_meshtastic_Paxcount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.meshtastic.proto.PaxcountProtos.Paxcount.class, org.meshtastic.proto.PaxcountProtos.Paxcount.Builder.class);
      }

      // Construct using org.meshtastic.proto.PaxcountProtos.Paxcount.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        wifi_ = 0;

        ble_ = 0;

        uptime_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.meshtastic.proto.PaxcountProtos.internal_static_meshtastic_Paxcount_descriptor;
      }

      @java.lang.Override
      public org.meshtastic.proto.PaxcountProtos.Paxcount getDefaultInstanceForType() {
        return org.meshtastic.proto.PaxcountProtos.Paxcount.getDefaultInstance();
      }

      @java.lang.Override
      public org.meshtastic.proto.PaxcountProtos.Paxcount build() {
        org.meshtastic.proto.PaxcountProtos.Paxcount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.meshtastic.proto.PaxcountProtos.Paxcount buildPartial() {
        org.meshtastic.proto.PaxcountProtos.Paxcount result = new org.meshtastic.proto.PaxcountProtos.Paxcount(this);
        result.wifi_ = wifi_;
        result.ble_ = ble_;
        result.uptime_ = uptime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.meshtastic.proto.PaxcountProtos.Paxcount) {
          return mergeFrom((org.meshtastic.proto.PaxcountProtos.Paxcount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.meshtastic.proto.PaxcountProtos.Paxcount other) {
        if (other == org.meshtastic.proto.PaxcountProtos.Paxcount.getDefaultInstance()) return this;
        if (other.getWifi() != 0) {
          setWifi(other.getWifi());
        }
        if (other.getBle() != 0) {
          setBle(other.getBle());
        }
        if (other.getUptime() != 0) {
          setUptime(other.getUptime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                wifi_ = input.readUInt32();

                break;
              } // case 8
              case 16: {
                ble_ = input.readUInt32();

                break;
              } // case 16
              case 24: {
                uptime_ = input.readUInt32();

                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int wifi_ ;
      /**
       * <pre>
       * seen Wifi devices
       * </pre>
       *
       * <code>uint32 wifi = 1;</code>
       * @return The wifi.
       */
      @java.lang.Override
      public int getWifi() {
        return wifi_;
      }
      /**
       * <pre>
       * seen Wifi devices
       * </pre>
       *
       * <code>uint32 wifi = 1;</code>
       * @param value The wifi to set.
       * @return This builder for chaining.
       */
      public Builder setWifi(int value) {
        
        wifi_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * seen Wifi devices
       * </pre>
       *
       * <code>uint32 wifi = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWifi() {
        
        wifi_ = 0;
        onChanged();
        return this;
      }

      private int ble_ ;
      /**
       * <pre>
       * Seen BLE devices
       * </pre>
       *
       * <code>uint32 ble = 2;</code>
       * @return The ble.
       */
      @java.lang.Override
      public int getBle() {
        return ble_;
      }
      /**
       * <pre>
       * Seen BLE devices
       * </pre>
       *
       * <code>uint32 ble = 2;</code>
       * @param value The ble to set.
       * @return This builder for chaining.
       */
      public Builder setBle(int value) {
        
        ble_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Seen BLE devices
       * </pre>
       *
       * <code>uint32 ble = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBle() {
        
        ble_ = 0;
        onChanged();
        return this;
      }

      private int uptime_ ;
      /**
       * <pre>
       * Uptime in seconds
       * </pre>
       *
       * <code>uint32 uptime = 3;</code>
       * @return The uptime.
       */
      @java.lang.Override
      public int getUptime() {
        return uptime_;
      }
      /**
       * <pre>
       * Uptime in seconds
       * </pre>
       *
       * <code>uint32 uptime = 3;</code>
       * @param value The uptime to set.
       * @return This builder for chaining.
       */
      public Builder setUptime(int value) {
        
        uptime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Uptime in seconds
       * </pre>
       *
       * <code>uint32 uptime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUptime() {
        
        uptime_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:meshtastic.Paxcount)
    }

    // @@protoc_insertion_point(class_scope:meshtastic.Paxcount)
    private static final org.meshtastic.proto.PaxcountProtos.Paxcount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.meshtastic.proto.PaxcountProtos.Paxcount();
    }

    public static org.meshtastic.proto.PaxcountProtos.Paxcount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Paxcount>
        PARSER = new com.google.protobuf.AbstractParser<Paxcount>() {
      @java.lang.Override
      public Paxcount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Paxcount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Paxcount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.meshtastic.proto.PaxcountProtos.Paxcount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meshtastic_Paxcount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meshtastic_Paxcount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031meshtastic/paxcount.proto\022\nmeshtastic\"" +
      "5\n\010Paxcount\022\014\n\004wifi\030\001 \001(\r\022\013\n\003ble\030\002 \001(\r\022\016" +
      "\n\006uptime\030\003 \001(\rBd\n\024org.meshtastic.protoB\016" +
      "PaxcountProtosZ\"github.com/meshtastic/go" +
      "/generated\252\002\024Meshtastic.Protobufs\272\002\000b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_meshtastic_Paxcount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meshtastic_Paxcount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meshtastic_Paxcount_descriptor,
        new java.lang.String[] { "Wifi", "Ble", "Uptime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
